plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.doris.extension'
}

ext {
    extName = 'HydraHD'
    extClass = '.HydraHD'
    themeSource = 'single'
    libVersion = '1'
    codeVersion = 1
}

android {
    defaultConfig {
        applicationId "eu.kanade.tachiyomi.extension.en.hydrahd"
        versionCode 1
        versionName "1.0"
    }
}